---
title: Syllabus
output:
  blogdown::html_page:
    toc: true
    fig_caption: false
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```

# Course Description

This finance course is the only one required in the MBA program. Within our term of study we aim to provide students with a solid financial background, which entails two components. Firstly, we seek for our students to acquire substantial practical skills and understanding of the subject matter which can be leveraged for use in both analytical and industry settings. Secondly, we aim to provide a base of financial education that can be used for further academic study. To meet these goals we present a body of theory central to the understanding of the issues in finance and a set a tools and techniques of financial analysis which are widely considered to be fundament. 

# Course Objectives

This course provides you with a framework with which to analyze individual and corporate investment and financing decisions. We will introduce the concepts of time and risk, which are the foundation for all financial decisions. We will then apply these concepts to the valuation of individual securities, such as stocks and bonds, and to capital investments undertaken by corporations.

Through this framework, we will gain an understanding of financial markets and the process by which companies make their investment decisions.

# Course Materials

## Text

Corporate Finance, 4th Edition, Berk, DeMarzo and Strangeland 

## Other recommended material

Subscription to the Wall Street Journal and/or the Financial Times. Some other excellent financial magazines such as The Economist and Business Week also provide good applications of what you will learn in the class.

## Course Website

The course website provides valuable information related to the course. On the website you will find:
- Smith Living Cases
- Lecture slides
- Additional material from academic journals, financial press, as may arise in class

# Evaluation
- Assignments/Case Study Reports: 30% 
- Presentation/Class Participation: 30% 
- Final Exam: 40% 


# Class Structure

Each class will consist of an introduction and overview of the topic, followed by a breakout activity which will consist of the students forming groups to answer a question or develop a discussion of an application of the topic. Following the breakout, the class will proceed into the specific applications and technical applications of the topic that was introduced. 

Each class will have an assignment or case associated with it. We will either have a case OR an assignment on a given class. This case will be presented by the students on case days. Even if you are not presenting, you are expected to have read these prior and to have (hopefully) thought about them and taken some notes. Each case has questions associated with them that you will be required to answer as part of your evaluation.

# Group Policy

You are required to deal with group dynamics within the group. You are required to remain with your group throughout the course. Working in a team is an important part of life. Good groups are based on skill-sets; no group needs 5 project managers or 5 programmers. Find people’s complementary skills to help create a good dynamic that maximizes productivity for each project. The idea is to excel and not to simply **fit in**.

# Assignments

Assignments will be given after each class and are due by the commencement of the following class. The assignments are designed to reinforce the procedures we have covered in the lecture and to get you to consider financial decision making in a real world setting. These assignments are individual pieces of evaluation, as a result, each student will need to submit their own work.

Assignment due dates: August 11th, August 21st, 11:59pm.

# Cases

Cases will be given at 2 intervals this semester. Evaluation of cases consists of answering the questions associated and applying skills that you have learned in the course to the case questions. In addition, students will be required to present these cases to the rest of the class. These presentations should focus on resolving the issue described in the case using financial analysis and financially backed reasoning. These cases and question submissions are group work. Details on how groups function are found in the section “Group Policy”. Case questions are due 2 Classes after the presentations are conducted.

# E-mail Policy

I am usually quick to respond to e-mails, however I am not always available for all types of questions. Essentially, if your question involves the structure of the course, curiosities about specific deadlines or marking should be handled by the TAs. You can reach them at their e-mails listed below. 
A good reason to e-mail me would be when you have read the material associated with a lecture, attended the lecture, asked classmates, reviewed the material, and you still do not understand something about the course. If this is the case, I would be happy to help you work through any issues.
Teaching Assistant Emails: [Eric Dong](mailto:eric.dong@queensu.ca) & [Neal Willcott](mailto:neal.willcott@queensu.ca) – they’re good guys.

# Academic Integrity

Queen’s students, faculty, administrators, and staff all have responsibilities for supporting and upholding the fundamental values of academic integrity. Academic integrity is constituted by the five core fundamental values of honesty, trust, fairness, respect, and responsibility, and by the quality of courage (see www.academicintegrity.org). These values and qualities are central to the building, nurturing, and sustaining of an academic community in which all members of the community will thrive. Adherence to the values expressed through academic integrity forms a foundation for the “freedom of inquiry and exchange of ideas” essential to the intellectual life of the University.
Students are responsible for familiarizing themselves with, and adhering to, the regulations concerning academic integrity. General information on academic integrity is available at Academic Integrity @ Queen’s University; an overview of Smith’s own policies and procedures are also important to review. You may also find these frequently asked questions on academic integrity helpful for your understanding of the concept and the regulations surrounding it. Departures from academic integrity include, but are not limited to, plagiarism, use of unauthorized materials, facilitation, forgery, and falsification. Actions which contravene the academic integrity regulations carry sanctions that can range from a warning, to loss of grades on an assignment, to failure of a course, to requirement to withdraw from the university.

# Class Schedule

## Class 1

### Overview
Topics covered: Introduction to corporate finance and capital markets <br>
*Read: Berk, DeMarzo and Strangeland - Chapter 1*

### Time Value of Money
Topics covered: Application of Time Value of Money to growth rates, compound interest rates, annuity and growing annuity, perpetuity and growing perpetuity. <br>
*Read: Berk, DeMarzo and Strangeland - Chapter 4*

Assignment 1

## Class 2

### Capital Budgeting

Topics covered: Capital budgeting as a procedure for evaluating the acquisition of long-term assets. Capital Budgeting and Taxation. Discussion on why firms make decisions on types of capital acquisition. <br>
*Read: Berk, DeMarzo and Strangeland - Chapter 8,9* <br>
*Case: TBD*

## Class 3

### Financial Forecasting

Topics covered: Taking past financial data along with management’s expectations and objectives and translating them to the future financial position of the company. Financial statement analysis, growth policy, external funds requirements.<br>
*Read: Berk, DeMarzo and Strangeland - Chapter 22* <br>
*Case: TBD*

## Class 4

### Firm and Securities Valuation

Topics covered: The fundamentals of security pricing and the impact on a company’s valuation from a market perspective. DCF( DDM, FCFE, FCFF). <br>
*Read: Berk, DeMarzo and Strangeland- Chapter 6, 7 *<br>
*Case: TBD*

## Class 5

### Risk and Return of the Capital Market

Topics covered: Impact of risk on value. Portfolio diversification and risk. CAPM (Capital Market Line, Security Market Line), performance valuation (Sharpe Ratio), solving for efficient sets.<br>
*Read: Berk, DeMarzo and Strangeland- Chapter 10, 11, 22* <br>
*Case: TBD*

## Class 6

### Cost of Capital

Topics covered: Calculations of Weighted-Average cost of capital (WACC), discussion of what impacts cost of capital and how this impacts firm decisions. <br>
*Read: Berk, DeMarzo and Strangeland- Chapter 14 *<br>
*Assignment 2*

## TA Sessions

There will be three TA sessions (dates TBD). These sessions will consist of the presentation of topics covered by the scope of the course. These session are built in conjunction with the students, so the TAs may ask you for topics to address in these time slots to better prepare you for exams or to review topics that you would like to dedicate more time. 

# Disabilities Policy

Students with physical and learning disabilities must contact the instructor as soon as possible in order for accommodations to be made. Queen’s University is committed to achieving full accessibility for persons with disabilities. Part of this commitment includes arranging academic accommodations for students with disabilities to ensure they have an equitable opportunity to participate in all of their academic activities. If you are a student with a disability and think you may need accommodations, you are strongly encouraged to contact Queen’s Student Accessibility Services (QSAS) and register as early as possible. For more information, including important deadlines, please visit the [QSAS website](https://www.queensu.ca/studentwellness/accessibility-services/).

